# Generated by Django 5.1.7 on 2026-02-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of the news')),
                ('content', models.TextField(blank=True, verbose_name='Content of the news')),
                ('is_published', models.BooleanField(choices=[(0, 'Draft'), (1, 'Published')], default=1, verbose_name='Is published')),
                ('image', models.ImageField(default='', upload_to='news/', verbose_name='Image')),
                ('url', models.SlugField(allow_unicode=True, max_length=160)),
            ],
        ),
    ]
