# Generated by Django 6.0.2 on 2026-02-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_author_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True),
        ),
    ]
