# Generated by Django 6.0.2 on 2026-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Description of the solution')),
                ('image', models.ImageField(default='', upload_to='game/', verbose_name='Image')),
            ],
        ),
    ]
