# Generated by Django 6.0.2 on 2026-02-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameproblems',
            name='slug',
        ),
    ]
