# Generated by Django 6.0.2 on 2026-02-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gameproblems_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameproblems',
            name='image',
        ),
    ]
