# Generated by Django 6.0.2 on 2026-02-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gameproblems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameproblems',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
